### ISSUE TITLE
[Improvement] Nmap Options

### ISSUE THREAD

**Issue by pchristod** [johannesschaefer/webnettools#1]
Hey,

I found your container coincidentally via a Pull Request you submitted to the testssl repo. I really like the idea to have those tools in a web frontend. Especially in a Docker container, this makes things very easy. It works very well on my Synology NAS, just set it up in Docker. 

Maybe a question for the future: Nmap is quite limited in this container, are there any plans on making more of it's native options available (UDP Scan, Port Ranges etc. and so on) for use?

Thanks!

**Comment by johannesschaefer** [comment]
Hi,
thanks for your request. It is not a big deal to add more options.
Do you have a list of options you need (with command line example). Nmap is very powerful and I don't want to offer all.

**Comment by pchristod** [comment]
Hi,

thank you for answering!
Yes sure, I would probably name the following (keep in mind that this is only my personal preference):
-sU: UDP Scan
-PN: Treat all hosts as online -- skip host discovery
-p <port ranges>: Only scan specified ports
--top-ports <number>: Scan <number> most common ports
 -v: Increase verbosity level (use twice or more for greater effect)

Understandable that not everything can be offered as there are way too many.

**Comment by johannesschaefer** [comment]
Please check the new 1.1.0 version. I added some more options to nmap.

**Comment by pchristod** [comment]
Thank you. Just pulled the latest image and it's working beautifully :)

**Comment by pchristod** [comment]
@johannesschaefer I forgot one thing. I do have a question. It seems that some options require root rights to be run in Nmap (e.g. UDP Scan). How can that be achieved with the Docker container?

**Comment by johannesschaefer** [comment]
With the 1.1 release I changed the user in the docker file to the standard admin user. On my Mac UDP scan is now working quite well.
I assume, that the containers on you NAS running in a less privileged mode. 
Maybe check this thread: https://community.synology.com/enu/forum/17/post/94853

**Comment by pchristod** [comment]
You are totally right, I forgot about the --privileged option. Had even used that with other containers...
For anyone coming across that problem in the future simply add that option and it will work. 
Thanks for implementing the suggestion & the help 👍

**Comment by drwetter** [comment]
Please allow me to chime in. ;-)

I would rather recommend to seek a solution which enables scanning without root (like currently, as I understand and not --priviliged  like ``setcap``. Good example here:  https://raesene.github.io/blog/2017/07/23/network-tools-in-nonroot-docker-images/.

PS: Running in privileged mode is highly discouraged for security reasons. Basically the container has more or less full access to the underlying OS (through access to ``/dev``, ``/sys`` and ``/proc``).  Also it runs under full ~40 set of Linux capabilities, instead of the usual 14.

**Comment by johannesschaefer** [comment]
Thanks for the hints and the link.
Unfortunately it is not working for me 😟.
I tried to include the setcap in my docker file. https://github.com/johannesschaefer/webnettools/blob/setcap/src/main/docker/Dockerfile.jvm
But as long as I run the tools with the non admin user, the tools are complaining about missing privileges.

**Comment by drwetter** [comment]
OT but related"

```
# Before building the container image run:
#
# ./mvnw package
```

You don't mean mvn?

**Comment by johannesschaefer** [comment]
mvn is correct, but the original Quarkus setup was using the maven wrapper. This project requires the maven command mvnw.

**Comment by johannesschaefer** [comment]
Just created an own thread for the security questions.
https://github.com/johannesschaefer/webnettools/issues/2
