### ISSUE TITLE
long healthcheck is preventing traefik from taking container online 

### ISSUE THREAD

**Issue by ogmueller** [johannesschaefer/webnettools#4]
Tools like traefik need the container to be "healthy" and not "starting" to take them online.

This healthcheck will actually take it online after 5 minutes:
`HEALTHCHECK --interval=5m --timeout=3s --start-period=15s`

The issue is, that the check is done immediately, BUT within the starting period a failed check is no reason to restart the container. So the next check is after 5m. Pretty long.

This is from docker documentation:
```
start period provides initialization time for containers that need time to bootstrap. Probe failure during that period will not be counted towards the maximum number of retries. However, if a health check succeeds during the start period, the container is considered started and all consecutive failures will be counted towards the maximum number of retries.
```

**Comment by johannesschaefer** [comment]
Fixed with version 1.3.0.
